<<<<<<< HEAD
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
=======
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Virtual Coding IDE",
  description: "Modern virtual coding workspace",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr" className="dark">
      <body>{children}</body>
    </html>
  );
>>>>>>> 08965590e2c08d064fd7397f8e044d8fc77b097d
}
